language: android

branches:
  only:
    - develop
    - /^v\.\d+\.\d+\.\d+$/
    - /^v\.\d+\.\d+\.\d+.\d+$/

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.gradle/native
  - $HOME/.gradle/daemon
  - $HOME/.gradle/caches/jars-1
  - $HOME/.gradle/caches/2.10
jdk:
- oraclejdk8

before_script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer

before_install:
 - chmod +x gradlew

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
before_script:
- git submodule update --init
script: ./gradlew build -PdisablePreDex
deploy:
- provider: script
  script: ./gradlew publishApkRelease
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: ./gradlew crashlyticsUploadDistributionRelease;
  skip_cleanup: true
  on:
    branch: develop
notifications:
  slack:
    secure: EzftlFYHtgFuBpRsSleKtsA1PngiK/tKHw8WrFfFU69ehXvvdA1Bi5t+TBn9eFo4E5cRolrPuyMGn8HyMLYn1RFAvr3YcSPIll++92OeyV0C9Opx68aK3iCoIXuasZ0Id3By1mnjefRuQvMQShfHBe/7lbtPvip254H9QX57fl4=
before_install:
- openssl aes-256-cbc -K $encrypted_7d926816f25e_key -iv $encrypted_7d926816f25e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
